language: php

php:
  - 5.5
  - 5.6

before_install:
  - composer self-update

before_script:
  - composer install --prefer-source --no-interaction --dev

script:
  - mkdir -p build/logs
  - vendor/bin/phpspec run -f pretty

after_script:
  - php vendor/bin/coveralls -v
